---
auth:
 API_KEY: xxxxxxxxxxxxxxxxxxxxx
 CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxx
 ORG_ID: xxxxxxxxxxxxxxxxxxxxx@AdobeOrg
 TECHNICAL_ACCOUNT_ID: xxxxxxxxxxxxxxxxxxxxx@techacct.adobe.com
 PRIVATE_KEY: ./private.key
---